### ISSUE TITLE
文本预处理中one-hot编码处有翻译错误

### ISSUE THREAD

**Issue by zylhub** [MoyanZitto/keras-cn#1]
首先，感谢翻译人员的付出。

在文本预处理一节中，one-hot编码处的代码有误:
- [这里](http://keras-cn.readthedocs.io/en/latest/preprocessing/text/)给出的代码是`keras.preprocessing.text.text_to_word_sequence(text, 
  filters=base_filter(), lower=True, split=" ")`
- 而[原文](http://keras.io/preprocessing/text/)中是`keras.preprocessing.text.one_hot(text, n,
  filters=base_filter(), lower=True, split=" ")`

**Comment by MoyanZitto** [comment]
@sherlockzoom 已处理，多谢！
