### ISSUE TITLE
Embedding和Word2Vec区别

### ISSUE THREAD

**Issue by yapingzhao** [MoyanZitto/keras-cn#137]
请问下，神经网络机器翻译模型中Embedding层作用和Word2Vec主要区别在哪里？
Embedding层是否也是利用像Word2Vec工具的词向量模型（Skip ngram或CBOW词袋子）进行训练得到词向量的？谢谢！

**Comment by Cherrymelon** [comment]
word2vec是一个算法,embedding是一个实现词-向量转换功能的api.
是的
