### ISSUE TITLE
Why can't I set the batch_size larger than 512

### ISSUE THREAD

**Issue by Franklin-Yao** [MoyanZitto/keras-cn#15]
I am using Tian X to train AlexNet. The input is 3227227 and when I set the batch_size in fit function, it will break down. As far as I know, Titan X has 12 GB memory. When I use a GPU with 1.5 GB memory, the batch_size can be 64. Why can't I set the batch_size larger than 512?

**Comment by MoyanZitto** [comment]
@xcmax 
为啥你希望你的batch_size大于512？大的batch容易撑爆显存，这么大的batch其实没有啥必要

**Comment by Franklin-Yao** [comment]
I finally found that my GPU is Titan not Titan x. Titan only has 6GB memory.
