### ISSUE TITLE
训练好的模型，载入时为什么还要预先编译一下？

### ISSUE THREAD

**Issue by wuk325** [MoyanZitto/keras-cn#18]

**Comment by MoyanZitto** [comment]
1. 使用load()载入模型或使用Application中的模型时，是编译好的，因此不需要再编译。
2. 编译是为了给模型进行一些如初始化方式，目标函数，优化器等方面的配置，如果你不需要做这种配置直接使用的话，也可以不编译。
3. 载入编译好的模型后你也可以再编译一次，没有问题。

所以预先编译一下怎么着你了……你就让人家预先编译一下不好么

**Comment by wuk325** [comment]
@MoyanZitto  我是这么想的，编译是用来配置模型的学习过程，训练好的模型已经不需要学习了，有权值有模型，我们完全可以利用我们的模型得到预测的结果输出，所以我感觉编译似乎没什么必要。

**Comment by MoyanZitto** [comment]
@wuk325 
是的，直接使用模型进行测试不需要进行编译。Keras的这个名字起的有点问题，因为compile并不是编译计算图的过程，而是configure的过程。真正的计算图编译在fit和predict中执行。

但这个是历史原因，之前版本的Keras是在compile里执行计算图编译的，后来某个版本改掉了。

**Comment by wuk325** [comment]
@MoyanZitto 哦哦 谢谢了

**Comment by MoyanZitto** [comment]
@wuk325 
Close this issue then.
