### ISSUE TITLE
怎么将预训练的权重载入新的模型

### ISSUE THREAD

**Issue by zhangyuxin621** [MoyanZitto/keras-cn#19]
我想写一个DNN的模型，用自编码器预训练
input_img = Input(shape=(39,))
encoded = Dense(32, activation='relu')(input_img)
encoded = Dense(16, activation='relu')(encoded)
encoded = Dense(8, activation='relu')(encoded)

decoded = Dense(16, activation='relu')(encoded)
decoded = Dense(32, activation='relu')(decoded)
decoded = Dense(39, activation='softmax')(decoded)

autoencoder = Model(input=input_img, output=decoded)
autoencoder.compile(optimizer='adadelta', loss='categorical_crossentropy')
这是预训练的模型，一共六层，保存在h5py中
h5py里的格式大概是这样的
HDF5 My.h5 
Group '/' 
    Attributes:
        'layer_names':  'input_1', 'dense_1', 'dense_2', 'dense_3', 'dense_4', 'dense_5', 'dense_6'
    Group '/dense_1' 
        Attributes:
            'weight_names':  'dense_1_W:0', 'dense_1_b:0'
        Dataset 'dense_1_W:0' 
            Size:  32x39
            MaxSize:  32x39
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
        Dataset 'dense_1_b:0' 
            Size:  32
            MaxSize:  32
            Datatype:   H5T_IEEE_F32LE (single)
            ChunkSize:  []
            Filters:  none
            FillValue:  0.000000
现在我用DNN又写了一个模型
model=Sequential()
input_img = Input(shape=(39,))
model = Dropout(0.2)(input_img)
model = Dense(32, activation='relu')(model)
model = Dropout(0.2)(model)
model = Dense(16, activation='relu')(model)
model = Dropout(0.2)(model)
model = Dense(8, activation='relu')(model)
model = Dropout(0.2)(model)
model = Dense(4, activation='softmax')(model)
DNN = Model(input=input_img, output=model)
sgd = SGD(lr=0.01, momentum=0.8, decay=0.0, nesterov=False);
DNN.compile(optimizer=sgd,loss='categorical_crossentropy',metrics=['accuracy'])

weights_path='.../My.h5'

DNN.load_weights('.../My.h5',True)
提示我不能将自编码器的8节点到16节点放入DNN的8节点到4节点，ValueError: Shapes (8, 4) and (8, 16) are not compatible
keras更新到1.1.0不是可以将权重载入到不同模型中吗，我该怎么设置才能载入进去？

**Comment by MoyanZitto** [comment]
@zhangyuxin621 
同学，载入不同模型的前提是名字要匹配，你可以print一下layer的name，看看能不能匹配的起？

最好将你关心的模型起下名字，比如Dense(32, name='fc1')什么的，这样就没问题了。

另外load_weights请使用关键在by_name，而不要只写一个True，目前这个写法没有错误，但不使用关键字存在参数匹配错误的风险。

**Comment by zhangyuxin621** [comment]
我改完以后是这样的，我前面自编码器的模型层名称是'input_1', 'dense_1', 'dense_2', 'dense_3', 'dense_4', 'dense_5', 'dense_6'我只用前四个
model=Sequential()
model.add(Dropout(0.2, input_shape=(39,),name='input_1'))
model.add(Dense(output_dim=32,name='dense_1',activation='relu'))
#model.add(Activation("relu"))
model.add(Dropout(0.2))
model.add(Dense(output_dim=16,name='dense_2',activation='relu'))
#model.add(Activation("relu"))
model.add(Dropout(0.2))
model.add(Dense(output_dim=8,name='dense_3',activation='relu'))
#model.add(Activation("relu"))
model.add(Dropout(0.2))
model.load_weights('.../My.h5' , by_name=True)
model.add(Dense(output_dim=4))
model.add(Activation("softmax"))
他提示了错误The name "dense_1" is used 2 times in the model. All layer names should be unique.不知道是怎么回事

**Comment by MoyanZitto** [comment]
@zhangyuxin621 
错误提示很清楚，“dense_1”的名字被使用了两次，有可能是最后一个dense层被自动命名为dense_1，虽然感觉这种可能性比较小，但如果是真的话那这就是个bug，我会再看看源代码看看自动生成名字有没有做相应防重名处理，你也再检查一下

**Comment by MoyanZitto** [comment]
@zhangyuxin621 
确认了，是个bug。我会尽快向官方提交修正后的代码，现在你可以通过不要把层名命名为“layer_1”这种形式或者显式的把最后一个Dense层命名为别的名字来防止此问题。

**Comment by zhangyuxin621** [comment]
好的，非常感谢

**Comment by MoyanZitto** [comment]
@zhangyuxin621
算了，感觉没有必要修这个bug……错误提示挺清楚的，也不是啥大问题~
