### ISSUE TITLE
关于不定长文本分类的问题，求教？

### ISSUE THREAD

**Issue by yinhao0214** [MoyanZitto/keras-cn#27]
对不定长文本分类，我想请教一下当padding成统一长度maxlen时，这个maxlen是如何取值的？目前我试验样本长短差距较大，短的几十个字，长的上千的字，请假一下maxlen取值有何经验？谢谢!

**Comment by fjck** [comment]
就用最长文本长度作为maxlen

**Comment by yinhao0214** [comment]
@fjck 好的，多谢
