### ISSUE TITLE
关于model.fit函数输出的问题

### ISSUE THREAD

**Issue by lizhiyuanUSTC** [MoyanZitto/keras-cn#30]
大家好，请问一下model.fit()函数将verbose设为1时输出的准确率是当前输入的batch的准确率还是整个训练集的准确率呢，我的batchsize时32，准确率输出是0.0347，这个应该不是batch的准确率吧

**Comment by MoyanZitto** [comment]
@lizhiyuanUSTC 
没仔细看过代码，粗略看了一下应该是每个batch更新，最后epoch结束时输出的是整个epoch的

**Comment by lizhiyuanUSTC** [comment]
@MoyanZitto 谢谢你的回答，我会去阅读源码的

**Comment by NYcleaner** [comment]
verbose为1这个准确率是每个batch的准确率
