### ISSUE TITLE
mnist和cifar10範例問題

### ISSUE THREAD

**Issue by hy-f** [MoyanZitto/keras-cn#32]
您好
想請問我將模型訓練好之後，怎麼利用自己的圖片去辨識分類呢?
要下的指令是什麼? 
不好意思我不是本科生，所以問題可能有點笨，謝謝。

**Comment by MoyanZitto** [comment]
@hy-f 
将你的图片组织成模型规定的形式，然后利用model.predict()获取分类结果。
如果你是想验证一下模型性能，请用model.evaluate()。

**Comment by hy-f** [comment]
您好
謝謝您的熱心回覆，可以給我一些範例程式碼(python)嗎?
非常感謝您。

**Comment by MoyanZitto** [comment]
@hy-f 
keras example 提供了一些范例的代码，cifar10_cnn.py就是一个很好的示例程序，但其中的数据集是keras处理好的。假设你已经训练好一个模型，名字叫“my_model”，并有一些测试图片位于/home/test_images中，要组织这些数据，你需要将图片读入到numpy数组里，按照模型的规定进行预处理，然后调用predict。我这里简单写一下程序，未经测试，理解意图即可：

``` python
from keras.preprocessing import image
from keras.models import load_model
import os
import numpy as np

image_dir = '/home/test_images'
model = load_model('my_model.h5')
os.chdir(image_dir)

data = []
for img_name in os.listdir(os.curdir):
    img = image.load_image(img_name, target_size = (3, 32, 32))
    img = image.img_to_array(img)
    data.append(img)

results = model.predict(np.array(data), batch_size = 10)
# you can also choose predict_proba or predict_classes for different purposes.

# followed by results analysis code.
```

**Comment by hy-f** [comment]
真的很感謝您，我正是需要這個！
我已經訓練好模型，也順利的儲存模型，要繼續研究了。

**Comment by hy-f** [comment]
您好
發生這個問題該怎麼解決呢?
我的測試圖為32*32的RGB圖，再麻煩您了。
謝謝。

Traceback (most recent call last):
  File "cifar10_use.py", line 16, in <module>
    results = model.predict(np.array(data), batch_size = 10)
  File "C:\Anaconda2\lib\site-packages\keras\models.py", line 671, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 1161, in predict
    check_batch_dim=False)
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 108, in standardize_input_data
    str(array.shape))
Exception: Error when checking : expected convolution2d_input_1 to have shape (None, 3, 32, 32) but got array with shape (10L, 3L, 3L, 32L)

**Comment by MoyanZitto** [comment]
@hy-f 
输入图像的shape不符。
输入的数据应为（None,3,32,32）的四阶tensor，第一维为batch维，第二维为channel维，后面两维为宽和高。
出问题的是第三维，建议print 输入数据的shape进行检查。

**Comment by hy-f** [comment]
您好
我是用官方的圖
https://www.cs.toronto.edu/~kriz/cifar.html
試過之後，還是出現一樣的error
不知道如何reshape...

**Comment by hy-f** [comment]
您好
我知道問題出在哪裡，我的backend是theano
所以target_size要改為(32,32,3)
非常感謝您！
