### ISSUE TITLE
如何在迭代结束或因为特殊原因终止时能够获取到验证准确率最优时的权重

### ISSUE THREAD

**Issue by ray0809** [MoyanZitto/keras-cn#33]
如题，因为我目前用的是earlystopping，虽然可以停止没必要的迭代，但我发现它只是探测一定次数的准确率未提升，所以如果我的准确率突然提升一段时间后一直逐渐下降，那它返回的最后一次的权重并不是最优时的权重。
以上是我目前想问的问题，望莫言大神帮忙解答一下，不甚感激！

**Comment by SCP-173-cool** [comment]
请查看http://keras-cn.readthedocs.io/en/latest/other/callbacks/内容。其中：
`keras.callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=0, save_best_only=False, save_weights_only=False, mode='auto')
`
该回调函数将在每个epoch后保存模型到filepath

filepath可以是格式化的字符串，里面的占位符将会被epoch值和传入on_epoch_end的logs关键字所填入

例如，filepath若为```weights.{epoch:02d-{val_loss:.2f}}.hdf5，则会生成对应epoch和验证集loss的多个文件。

**Comment by ray0809** [comment]
找到了，谢谢了！
