### ISSUE TITLE
keras在写程序时，开头会有np.random.seed(1337) ，这句话的作用是什么呢？

### ISSUE THREAD

**Issue by summerHaha** [MoyanZitto/keras-cn#34]
如题所述，求解答

**Comment by MoyanZitto** [comment]
@summerHaha 
Not a must.
This declaration set the random seed used in numpy, makes the experiment results reproducible.

**Comment by Petrinet** [comment]
每次产生的随机数 保持一样 利于训练分析  这是我认为的

**Comment by lizhiyuanUSTC** [comment]
保证网络初始化的时候能够得到同样的权重

**Comment by summerHaha** [comment]
谢谢大家的解答～～
