### ISSUE TITLE
关于多标签分类的问题

### ISSUE THREAD

**Issue by yinhao0214** [MoyanZitto/keras-cn#38]
请问keras可以实现多标签分类么，即样本的标签为[1,0,1,1,...]这样，已经知道一共有50个类别，每个样本可能同时有多个标签，请问这种分类该如何实现呢？

**Comment by MoyanZitto** [comment]
@FanhuaandLuomu 
Keras当然是可以实现的……但是怎么用loss和激活函数我最近也在研究，科研需要最近要看看多标签分类的原理= =有耐心的话等我搞清楚咋办再给你说

**Comment by yinhao0214** [comment]
@MoyanZitto 好的，我目前也在做多标签，多谢了

**Comment by MoyanZitto** [comment]
@fanhuaandLuomu
请参考Keras issue的#741，#2166
以及：http://link.springer.com/article/10.1007/s13748-014-0060-7

**Comment by yinhao0214** [comment]
@MoyanZitto ok，多谢
