### ISSUE TITLE
regression fit error

### ISSUE THREAD

**Issue by Franklin-Yao** [MoyanZitto/keras-cn#4]
Traceback (most recent call last):
  File "F:/python/ObGraspDec/GraspRegression.py", line 92, in <module>
    estimator.fit(X,Y)
  File "D:\anaconda2\lib\site-packages\keras\wrappers\scikit_learn.py", line 135, in fit
    **self.filter_sk_params(self.build_fn.**call**))
TypeError: **call**() takes at least 2 arguments (1 given)
# Code:

model=AlexNet(weights_path=None, ImageSize=ImageSize, NumOuput=NumOuput)
model.compile(loss='mean_squared_error', optimizer='adam')
seed = 7
np.random.seed(seed)
estimator = KerasRegressor(build_fn=model, nb_epoch=nb_epoch, batch_size=batch_size)
estimator.fit(X,Y)
# Any solution?

**Comment by MoyanZitto** [comment]
从traceback看出错的原因是scikit_learn.py第135行，这里的上下文代码是：

``` python
def fit(self, X, y, **kwargs):
        if self.build_fn is None:
            self.model = self.__call__(**self.filter_sk_params(self.__call__))
        elif not isinstance(self.build_fn, types.FunctionType):
            self.model = self.build_fn(
                **self.filter_sk_params(self.build_fn.__call__))
        else:
            self.model = self.build_fn(**self.filter_sk_params(self.build_fn))
```

不难看出，这是对self.model的构造，你这里的代码执行了elif语句，也就是 isinstance(self.build_fn, types.FunctionType)=False才会出现的情况，因为你传入的build_fn不是一个FunctionType，于是触发self.build_fn.**call**也就是model.**call**也就是model.call，而model.call是从输入tensor到输出tensor的映射，应该提供一个输入tensor作为参数，加上self参数一共是2个，但是这个输入tensor缺失（因为本来.call就不该在这里用），因此出现只提供了一个参数（self）的错误

我认为问题的主要原因是build_fn的类型，尽管没有自己运行过，我认为正常情况下程序应该走的是第三个分支条件（else），使用self.model = self.build_fn(**self.filter_sk_params(self.build_fn))这一句来构造model，请尝试朝这个方向进行debug，如果任何进展请留言。

**Comment by Franklin-Yao** [comment]
Thanks.I have solved this problem. @MoyanZitto
