### ISSUE TITLE
Exception: The shape of the input to "Flatten" is not fully defined

### ISSUE THREAD

**Issue by dorbodwolf** [MoyanZitto/keras-cn#5]
大家好，我在训练CNN时候出现如下异常：

> Traceback (most recent call last):
>   File "trainCNN.py", line 91, in <module>
>     **model.add(Flatten())**
>   File "C:\Anaconda2\lib\site-packages\keras\models.py", line 308, in add
>     output_tensor = layer(self.outputs[0])
>   File "C:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 514, in **call**
>     self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
>   File "C:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 572, in add_inbound_node
>     Node.create_node(self, inbound_layers, node_indices, tensor_indices)
>   File "C:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 152, in create_node
>     output_shapes = to_list(outbound_layer.get_output_shape_for(input_shapes[0]))
>   File "C:\Anaconda2\lib\site-packages\keras\layers\core.py", line 402, in get_output_shape_for
>     '(got ' + str(input_shape[1:]) + '. '
> **Exception: The shape of the input to "Flatten" is not fully defined (got (16, 0, 0). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.**

构建模型的代码如下：

`
"""
BUILD CNN NETWORK
"""
# generate a model

model = Sequential()
# first cnn layer

model.add(Convolution2D(4, 3, 3, border_mode='valid',batch_input_shape=(100, 5, 16, 16),  dim_ordering='th'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2), dim_ordering='th'))
# second cnn layer

model.add(Convolution2D(8,3,3, border_mode='valid', dim_ordering='th'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2), dim_ordering='th'))
# third cnn layer

model.add(Convolution2D(16, 3, 3, border_mode = 'valid', dim_ordering='th'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2), dim_ordering='th'))
# full-connect layer

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
# softmax classfication , output with 2 classes

model.add(Dense(2))
model.add(Activation('softmax'))

"""
train the model
"""
# using SGD and momentum
# sgd = SGD( lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)

model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
# using fit to train

model.fit(data, label, batch_size=100, nb_epoch=10, shuffle=True, verbose=1, validation_split=0.2)

`

**Comment by MoyanZitto** [comment]
你的图片大小太小了，16*16的图片如此多的Convolution和Pooling（尤其是Pooling）已经小到无法处理，建议增加数据shape或减少网络pooling层后再试。

**Comment by dorbodwolf** [comment]
@MoyanZitto 是这样的，我查看了model.summary()的输出，最后都没有像素了。还是谢谢你！

**Comment by MoyanZitto** [comment]
@dorbodwolf 没有像素是因为有太多的Pooling和Convolution层，因为每一层都会缩小输入图片的shape，如果确定是这个问题可以去除pooling层并将convolution2D的board_mode设为'same'
