### ISSUE TITLE
代码排版出现问题，缩进没有缩好

### ISSUE THREAD

**Issue by wwxFromTju** [MoyanZitto/keras-cn#54]
在[http://keras-cn.readthedocs.io/en/latest/models/sequential/](http://keras-cn.readthedocs.io/en/latest/models/sequential/)中，def generate_arrays_from_file(path):的缩进出现错误

**Comment by MoyanZitto** [comment]
@wwxFromTju 
多谢提醒，可否提交一个PR呢？
