### ISSUE TITLE
keras ImportError after openblas installed and configed

### ISSUE THREAD

**Issue by dorbodwolf** [MoyanZitto/keras-cn#6]
Hi,
when I am training keras in windows 64bit, I got the error as below:

> AssertionError: AbstractConv2d Theano optimizationfailed: there is no implementation available supporting the requested options.Did you exclude both "conv_dnn" and "conv_gemm" from theoptimizer? If on GPU, is cuDNN available and does the GPU support it? If onCPU, do you have a BLAS library installed Theano can link against?

then I fixed it by config pre-compiled openBLAS( https://sourceforge.net/projects/openblas/files/v0.2.8/
), the context of my config file .theanorc.txt is below:

> [global]
> floatX = float32
> device = cpu
> optimizer = None
> THEANO_FLAGS='optimizer_excluding=conv_dnn, optimizer_excluding=conv_gemm'
> [blas]
> ldflags = -LC:\OpenBLAS\lib –lopenblas

but when I train cnn again, it got ImportError

> ImportError: ('The following error happened while compiling the node', Elemwise{round_half_away_from_zero,no_inplace}(Softmax.0), '\n', 'DLL load failed: \xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\xa8\xb5\xc4\xb3\xcc\xd0\xf2\xa1\xa3', '[Elemwise{round_half_away_from_zero,no_inplace}()]')

I cannot find trick of this trouble, who can provide help? I am appreciating your kindness.

from dorbodwolf-兰州

**Comment by MoyanZitto** [comment]
@dorbodwolf 
1. 在windows上配置keras请参考http://keras-cn.readthedocs.io/en/latest/getting_started/keras_windows/
2. 如有可能，建议不要使用windows配置keras，linux的配置方法文档中也有详细说明
3. 如按照1的指导没有配置成功，请留言告知，我将咨询SCP-173

**Comment by dorbodwolf** [comment]
@MoyanZitto  我已经转战linux,成功训练cnn,非常感谢社群!谢谢
不过windows下按照文档的说明安装keras应该是有漏洞的
