### ISSUE TITLE
文档linux安装部分笔误

### ISSUE THREAD

**Issue by boozyguo** [MoyanZitto/keras-cn#7]
在“http://keras-cn.readthedocs.io/en/latest/getting_started/keras_linux/”页中：
”之后source gedit /etc/bash.bashrc即可“，这句可能是笔误。

**Comment by MoyanZitto** [comment]
多谢，确认后即刻修改，感谢对keras-cn的支持

**Comment by xzqjack** [comment]
@boozyguo 
已经修正,多谢
