### ISSUE TITLE
Some misspellings in FAQ

### ISSUE THREAD

**Issue by gdbb** [MoyanZitto/keras-cn#74]
In the part named "如何在Keras中使用预训练的模型？"

`from keras.applications.vgg16 impoprt VGG16 `
`from keras.applications.vgg19 impoprt VGG19 `
`from keras.applications.resnet50 impoprt ResNet50 `
`from keras.applications.inception_v3 impoprt InceptionV3 `

"impoprt" should be "import".

**Comment by ypwhs** [comment]
https://github.com/MoyanZitto/keras-cn/pull/77
