### ISSUE TITLE
theanorc配置文件

### ISSUE THREAD

**Issue by boozyguo** [MoyanZitto/keras-cn#8]
在“http://keras-cn.readthedocs.io/en/latest/getting_started/keras_linux/”页中，
theanorc文件的配置开头少了[global]：

**_[global]_**
openmp=False 
device = gpu  
floatX = float32  
allow_input_downcast=True  
[lib]
cnmem = 0.8 
[blas]
ldflags= -lopenblas
[nvcc]
fastmath = True

**Comment by MoyanZitto** [comment]
@boozyguo
多谢，确认后马上修改

**Comment by MoyanZitto** [comment]
@boozyguo 
已经修正,多谢!
